/**
 * AdtRequest - High-level CRUD operations for Transport Request objects
 *
 * Creatable, readable and modifiable — with automatic operation chains,
 * error handling, and resource cleanup.
 *
 * Uses low-level functions directly (not Builder classes).
 *
 * Session management:
 * - No stateful needed for transport operations
 * - Transport requests don't use lock/unlock
 *
 * Operation chains:
 * - Create: create (no validation, no check, no activate)
 * - Read: read (get transport request details)
 * - Update: GET current XML, patch the description, PUT (read-modify-write —
 *   the only field ADT lets a client change on a request)
 * - Delete: DELETE the item resource (ADT accepts this only for an empty request)
 * A transport request is created, read, described anew and deleted while empty.
 * It is not activated, has no syntax check, no lock, no version history, and no
 * transport of its own — and no validation: its number is generated by the
 * system, so there is nothing to check before creating one.
 */

import type {
  IAbapConnection,
  IAdtCreatable,
  IAdtDeletable,
  IAdtError,
  IAdtMetadataReadable,
  IAdtMetadataUpdatable,
  IAdtOperationOptions,
  IAdtReadable,
  IAdtRequest,
  IAdtResponse,
  IAdtSystemContext,
  IAdtUpdatable,
  IAnalyse,
  IDeferredResponseConnection,
  IListTransportsOptions,
  ILogger,
  IResultStrategy,
} from '@mcp-abap-adt/interfaces';
import { TRANSPORT_SEARCH_CONFIGURATIONS_URL } from '@mcp-abap-adt/interfaces';
import { TransportSearchConfigurationMissing } from '../../utils/adtErrors';
import { answering } from '../../utils/adtResponse';
import { createTransport } from './create';
import { deleteTransport } from './delete';
import { getTransportSearchConfigurations, listTransports } from './list';
import { parseTransportTree } from './parseTransportTree';
import { getTransport } from './read';
import {
  type ITransportConfig,
  type ITransportResults,
  type ITransportTree,
  transportDocuments,
} from './types';
import { updateTransport } from './update';

/**
 * Whether awaiting this connection's answers is safe right now.
 *
 * It left `@mcp-abap-adt/interfaces` in 29.0.0 with everything else that
 * emitted code: the contract declares `IDeferredResponseConnection`, and the
 * narrowing over it is an implementation.
 *
 * Not a proof of absence — a third-party connection that defers answers without
 * declaring it will still deadlock. It makes the known case honest.
 */
export function hasDeferredResponses<T extends object>(
  connection: T,
): connection is T & IDeferredResponseConnection {
  return (
    (connection as Partial<IDeferredResponseConnection>)
      .responsesAreDeferred === true
  );
}

export class AdtRequest<
  R extends ITransportResults<
    unknown,
    unknown,
    unknown,
    unknown,
    unknown,
    unknown
  > = ITransportResults,
> implements
    IAdtCreatable<ITransportConfig, ReturnType<R['created']>>,
    IAdtMetadataReadable<ITransportConfig, ReturnType<R['metadata']>>,
    IAdtMetadataUpdatable<ITransportConfig, ReturnType<R['metadataUpdated']>>,
    IAdtDeletable<
      ITransportConfig,
      ReturnType<R['deleted']>,
      ReturnType<R['deletionCheck']>
    >,
    IAdtRequest<ReturnType<R['list']>>
{
  private readonly connection: IAbapConnection;
  private readonly logger?: ILogger;
  private readonly systemContext: IAdtSystemContext;
  public readonly objectType: string = 'Request';

  constructor(
    connection: IAbapConnection,
    logger?: ILogger,
    systemContext?: IAdtSystemContext,
    // The one cast in this file, and it is on the default. See AdtClass.
    protected readonly results: R = transportDocuments as unknown as R,
  ) {
    this.connection = connection;
    this.logger = logger;
    this.systemContext = systemContext ?? {};
  }

  /** The request number, or the caller's mistake. */
  private number(config: Partial<ITransportConfig>): string {
    if (!config.transportNumber) {
      throw new Error('Transport request number is required');
    }
    return config.transportNumber;
  }

  /**
   * Create a transport request.
   *
   * The number is the system's to generate, so there is nothing to validate
   * before the POST — which is why this module has no `validate`.
   */
  async create<E extends IAdtError = IAdtError>(
    config: ITransportConfig,
    options?: IAdtOperationOptions<E>,
  ): Promise<IAdtResponse<ReturnType<R['created']>, E>> {
    if (!config.description) {
      throw new Error('Transport request description is required');
    }

    this.logger?.info?.('Creating transport request');
    return answering(
      () =>
        createTransport(this.connection, {
          transport_type:
            config.transportType === 'customizing'
              ? 'customizing'
              : 'workbench',
          description: config.description,
          target_system: config.targetSystem,
          owner: config.owner ?? this.systemContext.responsible,
        }),
      this.results.created as IResultStrategy<ReturnType<R['created']>>,
      options?.analyse,
    );
  }

  /**
   * The request's own document: its description, owner and tasks.
   *
   * A transport request has no source, so this is the whole of reading one —
   * which is why the type composes `IAdtMetadataReadable` and nothing else.
   * There used to be a `read` beside this whose body was `return
   * this.readMetadata(...)`; one endpoint behind two members, admitted in the
   * code.
   */
  async readMetadata<E extends IAdtError = IAdtError>(
    config: Partial<ITransportConfig>,
    options?: { withLongPolling?: boolean } & IAdtOperationOptions<E>,
  ): Promise<IAdtResponse<ReturnType<R['metadata']>, E>> {
    const number = this.number(config);

    return answering(
      () => getTransport(this.connection, number),
      this.results.metadata as IResultStrategy<ReturnType<R['metadata']>>,
      options?.analyse,
    );
  }

  /**
   * The transport requests the server lists.
   *
   * Until 30.0.0 this resource had three members — `list`, `listNodes`, and a
   * `listNodes<T>(parse, …)` overload — which answered the identical document
   * read to three different depths. One request, one member: the reading is
   * chosen when this implementation is constructed, and the tree is the
   * default because it is the only one that carries the containers, the
   * description and the language a request holds.
   *
   * With `configUri`: one request. Without: two — the configurations, then the
   * list. The five filter parameters this used to take were never read by the
   * server; filtering is a property of the saved configuration.
   */
  async list(
    options?: IListTransportsOptions,
  ): Promise<IAdtResponse<ReturnType<R['list']>>> {
    const configUri =
      options?.configUri ?? (await this.resolveSearchConfiguration());

    this.logger?.info?.('Listing transport requests', { configUri });
    return answering(
      () => listTransports(this.connection, { configUri }),
      this.results.list as IResultStrategy<ReturnType<R['list']>>,
    );
  }

  /**
   * Which saved search to run when the caller named none.
   *
   * Deterministic or it throws — never "the first one", which would silently
   * run somebody else's filters.
   *
   * The deferred-connection check lives HERE and not in `list()`: an explicit
   * `configUri` waits for nothing, so a batch call that supplies one is
   * legitimate. Guarding earlier would reject it.
   */
  protected async resolveSearchConfiguration(): Promise<string> {
    if (hasDeferredResponses(this.connection)) {
      throw new Error(
        'configUri is required on a batch client: resolving a search ' +
          'configuration needs a response that a batch cannot deliver until ' +
          'execute().',
      );
    }

    const configurations = await getTransportSearchConfigurations(
      this.connection,
    );

    if (configurations.length === 0) {
      throw new TransportSearchConfigurationMissing(
        TRANSPORT_SEARCH_CONFIGURATIONS_URL,
      );
    }

    if (configurations.length === 1) {
      return configurations[0].uri;
    }

    // Several. Picking one would mean guessing which attribute marks a default,
    // and the payload on the only system we have carries no such marker — one
    // configuration cannot show what several would look like. So: say so, and
    // let the caller choose. This branch gets a rule when a system with several
    // configurations has actually been read.
    throw new Error(
      `This system has ${configurations.length} transport search configurations ` +
        'and none can be shown to be the default; pass configUri explicitly. ' +
        `Available: ${configurations.map((c) => c.uri).join(', ')}`,
    );
  }

  /**
   * Update the request's description.
   *
   * ADT's only mutable field on a request. Read-modify-write: GET the current
   * XML, patch the description into it, PUT it back — building the body from
   * scratch would drop every server-managed field the client does not model.
   */
  async updateMetadata<E extends IAdtError = IAdtError>(
    config: Partial<ITransportConfig>,
    options?: IAdtOperationOptions<E>,
  ): Promise<IAdtResponse<ReturnType<R['metadataUpdated']>, E>> {
    const number = this.number(config);
    if (!config.description) {
      throw new Error('Transport request description is required for update');
    }
    const description = config.description;

    this.logger?.info?.('Updating transport request description:', number);
    return answering(
      () => updateTransport(this.connection, number, description),
      this.results.metadataUpdated as IResultStrategy<
        ReturnType<R['metadataUpdated']>
      >,
      options?.analyse,
    );
  }

  /**
   * Delete the request.
   *
   * ADT accepts this only for a request that holds no objects; a non-empty
   * request is rejected by the server, not by this client.
   */
  /**
   * Ask whether the transport request can be deleted now.
   *
   * **The deletion service cannot answer this one, measured rather than
   * assumed.** A check for `/sap/bc/adt/cts/transportrequests/{n}` comes back
   * `No URI-Mapping defined for URI …` — the service resolves repository
   * objects through their package, and a transport request is not one. That
   * answer is a fact about the address this library chose, not about the
   * request, and a caller cannot act on it.
   *
   * So this asks the resource that *can* answer: the request itself. ADT
   * deletes only an empty, unreleased request, and both facts are in its own
   * document — `tm:task` entries and the objects under them. Reading the
   * verdict out of it is the `deletionCheck` strategy's job, which is why the
   * default hands the document over as it arrived.
   *
   * One request, like every other member; it is simply not the same one the
   * other twenty-nine types use.
   */
  async checkDeletion<E extends IAdtError = IAdtError>(
    config: Partial<ITransportConfig>,
    options?: IAdtOperationOptions<E>,
  ): Promise<IAdtResponse<ReturnType<R['deletionCheck']>, E>> {
    const number = this.number(config);

    return answering(
      () => getTransport(this.connection, number),
      this.results.deletionCheck as IResultStrategy<
        ReturnType<R['deletionCheck']>
      >,
      options?.analyse,
    );
  }

  async delete<E extends IAdtError = IAdtError>(
    config: Partial<ITransportConfig>,
    options?: IAdtOperationOptions<E>,
  ): Promise<IAdtResponse<ReturnType<R['deleted']>, E>> {
    const number = this.number(config);

    this.logger?.info?.('Deleting transport request:', number);
    return answering(
      () => deleteTransport(this.connection, number),
      this.results.deleted as IResultStrategy<ReturnType<R['deleted']>>,
      options?.analyse,
    );
  }
}
